project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources: 
    - config.json
  # - shinylive-sw.js

website:  
  # repo-url: https://github.com/coatless-quarto/r-shinylive-demo
  # repo-actions: [edit, issue]
  title: "AI task demos"
  navbar:
    search: false
    left:
      - text: "R-shinylive"
        file: index.qmd
      - text: "Python-shinylive"
        file: sl_python.qmd
      - text: "ojs"
        file: ojs.qmd
      - text: "Rep Study Followup"
        file: rep_followup.qmd

format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 200px
    toc: true

